site_name: SNT/NSI - Lycée Jean Prévost
docs_dir: docs-public

theme:
  name: material
  language: fr
  logo : assets/logo3.png
  favicon: assets/logo3.png
  palette:
    - scheme: default
      primary: green
      accent: lime
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - navigation.path
    - toc.integrate
    - header.autohide
    - navigation.instant
extra_css:
  - styles/site.css

validation:
  nav:
    omitted_files: ignore
not_in_nav: |
  /archives/**
  /echecs/**

nav:

  - Accueil: index.md

  - Seconde GT: SNT/index.md

  - Première NSI: 1NSI/index.md

  - Terminale NSI: TNSI/index.md

  - Années précédentes:
      - archives/index.md
      - 2025-2026: archives/2025-2026/index.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
