site_name:  M.Déhais - Professeur de NSI - Lycée Jean Prévost
docs_dir: docs-public

theme:
  name: material
  language: fr
  palette:
    - scheme: default
      primary: green
      accent: lime
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - toc.integrate  
extra_css:
  - styles/site.css

nav:
  - Accueil: index.md

  - SNT:
      - Accueil: SNT/index.md
      - Thématique 0 - Python: SNT/python/index.md
      - Thématique 1 - Internet: SNT/internet/index.md
      - Thématique 2 - Web: SNT/web/index.md

  - 1ère NSI:
      - Accueil: 1NSI/index.md

  - TNSI:
      - Accueil: TNSI/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences