site_name: SNT/NSI - Lycée Jean Prévost
docs_dir: docs-public

theme:
  name: material
  language: fr
  logo : assets/logo3.png
  favicon: assets/logo3.png
  palette:
    - scheme: default
      primary: green
      accent: lime
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes
    - toc.integrate
extra_css:
  - styles/site.css

nav:

  - Accueil: 
      - index.md
  - SNT: 
      - SNT : SNT/index.md
      
      - Thématique 0 - Python: SNT/python/index.md
      - Thématique 1 - Internet: SNT/internet/index.md
      - Thématique 2 - Web: SNT/web/index.md

  - 1ère NSI:
      -  1ère NSI : 1NSI/index.md
      
      - Thématique 1 - Langage et Programmation: 1NSI/python/index.md
      - Thématique 2 - Structures de données: 1NSI/donnees/index.md
      - Thématique 3 - Algorithmique: 1NSI/algo/index.md
      
      - TP notés: 1NSI/tp/index.md
      - Projets: 1NSI/projet/index.md


  - TNSI:
      -  TNSI : TNSI/index.md
      
      - Thématique 1 - Langage et Programmation: TNSI/python/index.md
      - Thématique 2 - Structures de données: TNSI/donnees/index.md
      - Thématique 3 - Base de données: TNSI/bdd/index.md
      - Thématique 3 - Architecture et OS: TNSI/architecture/index.md
      
      - TP notés: TNSI/tp/index.md
      - Projets: TNSI/projet/index.md

  - Club d'Echecs : echecs/index.md
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences



  